# Subreddit Gaming Dataset Cleaning

In this notebook, we are going to ONLY clean the dataset.  No processing data, no plots to show correlation between variables.  This is keep things nice and tidy by seperating the different parts of the project into their own notebooks. 

The only processing here will be combining 2 datasets of interest.

# Set-up

We set-up our environment here by importing pandas and numpy.

In [51]:
# import our tools
import pandas as pd
import numpy as np
from datetime import datetime

# Datasets

We have 2 datasets that we are interested in here.  The first is gaming_comments.csv that contains all comments made by redditors on the gaming subreddit for May 2018.  The other is gaming_posts.csv that contains all posts made on the gaming subreddit for May 2018.

In [52]:
# import gaming_comments
comments = pd.read_csv("gaming_comments.csv")
comments.head()

,body,score_hidden,archived,name,author,author_flair_text,downs,created_utc,subreddit_id,link_id,parent_id,score,retrieved_on,controversiality,gilded,id,subreddit,ups,distinguished,author_flair_css_class
0,"Lol come on kid, you don't have to act tough. ...",False,True,NaN,Bsteph21,NaN,NaN,1525438018,t5_2qh03,t3_7bpgu4,t1_dyfffkj,0,1527069617,0,0,dyfot01,gaming,NaN,NaN,NaN
1,"There were soany disappointments in GTA5, the ...",False,True,NaN,Z_JayJohn,NaN,NaN,1525419638,t5_2qh03,t3_7bpgu4,t1_dy2jctt,0,1527064696,0,0,dyfffkj,gaming,NaN,NaN,NaN
2,If it's very likely that your friends and fami...,False,True,NaN,Impact009,NaN,NaN,1525246808,t5_2qh03,t3_7by7xx,t1_dpmatdi,0,1526981701,0,0,dybb0tv,gaming,NaN,NaN,NaN
3,I had no idea this was here! Is it taboo to re...,False,True,NaN,Andylunique,NaN,NaN,1526059024,t5_2qh03,t3_7e675r,t1_dytfbys,0,1527350984,0,0,dytjlqp,gaming,NaN,NaN,NaN
4,If I recall correctly the DNC candidate last p...,False,True,NaN,HeldVenom,NaN,NaN,1525731042,t5_2qh03,t3_7ek4q6,t1_dq5t2ri,0,1527199825,0,0,dylxy4j,gaming,NaN,NaN,NaN

In [77]:
# import gaming_posts
posts = pd.read_csv("gaming_posts.csv")
posts.head()

C:\Users\AFKsi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,created_utc,subreddit,author,domain,url,num_comments,score,ups,downs,title,...,author_flair_css_class,archived,is_self,from_id,permalink,name,author_flair_text,quarantine,link_flair_text,distinguished
0,1525653984,gaming,l3lackl3ridge,hh,http://hh,0,1,1,0,yy,...,NaN,False,False,NaN,/r/gaming/comments/8hjnmt/yy/,t3_8hjnmt,NaN,NaN,NaN,NaN
1,1527269415,gaming,Nyfadon,if,http://If,0,1,1,0,Jeu,...,NaN,False,False,NaN,/r/gaming/comments/8m3k8c/jeu/,t3_8m3k8c,NaN,NaN,NaN,NaN
2,1527613615,gaming,[deleted],t.me,https://t.me/steamanalytics,0,1,1,0,I've build a little telegram channel operated ...,...,NaN,False,False,NaN,/r/gaming/comments/8n0rgh/ive_build_a_little_t...,t3_8n0rgh,NaN,NaN,NaN,NaN
3,1526617219,gaming,Samba-boy,nu.nl,https://nu.nl/games/5269283/ea-vingers-getikt-...,0,1,1,0,EA Sports is forbidden to advertise lootboxes ...,...,NaN,False,False,NaN,/r/gaming/comments/8kagur/ea_sports_is_forbidd...,t3_8kagur,NaN,NaN,NaN,NaN
4,1527150738,gaming,Bubblesfordinner,nu.nl,https://www.nu.nl/games/5280377/playstation-5-...,0,1,1,0,PlayStation 5 verschijnt op zijn vroegst in 2021,...,NaN,False,False,NaN,/r/gaming/comments/8lr2qw/playstation_5_versch...,t3_8lr2qw,NaN,NaN,NaN,NaN

# Cleaning Comments

Time to clean up the data to make is easier to process.  We're essentially clean it once for ease of processing and removal of really obvious not useful data.

We start by dropping the columns that are of no interest to us.

In [54]:
# create a list containing everything to be dropped
drop_list_comments = ["archived", "name", "author", "author_flair_text", "downs", "retrieved_on", "id", "subreddit",
                     "subreddit_id", "author_flair_css_class", "ups"]

# execute the drop
comments.drop(drop_list_comments, axis = 1, inplace = True)

# view the result
comments.head()

,body,score_hidden,created_utc,link_id,parent_id,score,controversiality,gilded,distinguished
0,"Lol come on kid, you don't have to act tough. ...",False,1525438018,t3_7bpgu4,t1_dyfffkj,0,0,0,NaN
1,"There were soany disappointments in GTA5, the ...",False,1525419638,t3_7bpgu4,t1_dy2jctt,0,0,0,NaN
2,If it's very likely that your friends and fami...,False,1525246808,t3_7by7xx,t1_dpmatdi,0,0,0,NaN
3,I had no idea this was here! Is it taboo to re...,False,1526059024,t3_7e675r,t1_dytfbys,0,0,0,NaN
4,If I recall correctly the DNC candidate last p...,False,1525731042,t3_7ek4q6,t1_dq5t2ri,0,0,0,NaN

As a reddit user, we know that some comments become "[deleted]" as someone might post a comment and then in regret, choose to delete it.  "[removed]" occurs when a moderator doesn't like your comment and chooses to remove it.  In both cases, these comments are useless to us because the main object of interest is missing, the body of the comment.  Hence, we remove them from here.

In [55]:
# create a list with the index of all comments that are [deleted] and [removed]
deleted_comments = comments.index[comments["body"] == "[deleted]"].tolist()
deleted_comments = comments.index[comments["body"] == "[removed]"].tolist()

# remove them from the dataset
comments.drop(comments.index[deleted_comments], inplace = True)

# quick check
"[deleted]" in comments

False

In [56]:
# same for the other
"[removed]" in comments

False

In [57]:
# reset the index for ease of later cleaning
comments.reset_index()

,index,body,score_hidden,created_utc,link_id,parent_id,score,controversiality,gilded,distinguished
0,0,"Lol come on kid, you don't have to act tough. ...",False,1525438018,t3_7bpgu4,t1_dyfffkj,0,0,0,NaN
1,1,"There were soany disappointments in GTA5, the ...",False,1525419638,t3_7bpgu4,t1_dy2jctt,0,0,0,NaN
2,2,If it's very likely that your friends and fami...,False,1525246808,t3_7by7xx,t1_dpmatdi,0,0,0,NaN
3,3,I had no idea this was here! Is it taboo to re...,False,1526059024,t3_7e675r,t1_dytfbys,0,0,0,NaN
4,4,If I recall correctly the DNC candidate last p...,False,1525731042,t3_7ek4q6,t1_dq5t2ri,0,0,0,NaN
5,5,Not going to argue when you cant even see it y...,False,1525957030,t3_7fo1rm,t1_dyhg867,0,0,0,NaN
6,6,It's a fucking 14 year old.....,False,1525962054,t3_7g1chd,t1_dqg6i5o,0,0,0,NaN
7,7,*cough* *cough* skyrim *cough*,False,1525463027,t3_7m08f4,t1_dygc6pv,0,0,0,NaN
8,8,"As much as i love both campaigns, you gotta re...",False,1525431827,t3_7m08f4,t1_drr5l6c,0,0,0,NaN
9,9,Developers want to make everything more multip...,False,1525454093,t3_7m08f4,t1_dyfw7u9,0,0,0,NaN
10,10,Wah wah wah.,False,1527006133,t3_7m1hei,t1_dv3d9q3,0,0,0,NaN
11,11,These 12 games is all they have almost a year ...,False,1525997695,t3_7n83n9,t1_drzunwh,0,0,0,NaN
12,12,"My subreddit recommendation game is top-notch,...",False,1527635187,t3_7p96u4,t1_dzshx32,0,0,0,NaN
13,13,"Nope.\n\n&gt;Welcome to /r/dontdeadopeninside,...",False,1527634652,t3_7p96u4,t1_dsfgk9p,0,0,0,NaN
14,14,No it wasn’t. Theoretically they could have go...,False,1525418690,t3_7x18az,t1_du5gxwh,0,0,0,NaN
15,15,never really played a Zelda. And to be honest...,False,1525422800,t3_7xtnmw,t1_dub8zqs,0,0,0,NaN
16,16,Only the fortnite wins matter not the grades,False,1527474941,t3_7xurnb,t1_dubgu8r,0,0,0,NaN
17,17,[deleted],False,1527146433,t3_7y2psy,t1_dzh47v5,0,0,0,NaN
18,18,[deleted],False,1527114736,t3_7y2psy,t1_dzgkmg2,0,0,0,NaN
19,19,"Opioids*.\n \nGo back to English class, stalke...",False,1527186840,t3_7y2psy,t1_dzhp57d,0,0,0,NaN
20,20,You weren't right and edited your comment to c...,False,1527121097,t3_7y2psy,t1_dzgy3t3,0,0,0,NaN
21,21,living with dial-up connection or better livin...,False,1526500783,t3_7yz15s,t1_dz3b2x9,0,0,0,NaN
22,22,Also I think this post should be kept alive. E...,False,1526532518,t3_7yz15s,t1_dz3b2x9,0,0,0,NaN
23,23,Mine still works fine\n,False,1527197971,t3_7yzs17,t1_dulalpy,0,0,0,NaN
24,24,"No,they're pocket monster not pocket animals.",False,1526038989,t3_7zr4rf,t1_duqkdrp,0,0,0,NaN
25,25,&gt;I've been a lot of places in my lifetime. ...,False,1527019312,t3_804p3s,t1_dutl09j,0,0,0,NaN
26,26,Just use GeForce experience optimization then,False,1525723890,t3_80e68k,t1_duuvdgy,0,0,0,NaN
27,27,Damn if only 8=====D \n\nYou’re the bitch boy ...,False,1525335214,t3_81k66k,t1_dy6nxv4,0,0,0,NaN
28,28,"That would be Yahtzee, from the channel zero p...",False,1527419858,t3_82qos7,t1_dvc2dps,0,0,0,NaN
29,29,68 days to come up with that response. Nice.,False,1526597901,t3_83a7ww,t1_dz5nera,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...
703752,716827,You cant really know that can you? Because the...,False,1527791474,t3_8nkn3v,t1_dzw7i80,-1,0,0,NaN
703753,716828,Has anyone ever modded one of these to run on ...,False,1527795580,t3_8nkzdi,t3_8nkzdi,-1,0,0,NaN
703754,716829,"Same desktop picture -1, task bar on both scre...",False,1527797681,t3_8nl3tq,t3_8nl3tq,-1,0,0,NaN
703755,716830,Ps4 sucks. Controllers are terrible,False,1527795131,t3_8nl6pc,t3_8nl6pc,-1,0,0,NaN
703756,716831,"Now Billy, the normies are listening, and i kn...",False,1527795296,t3_8nlb03,t3_8nlb03,-1,1,0,NaN
703757,716832,The dream police \nThey live inside of my hea...,False,1527810969,t3_8nlb03,t3_8nlb03,-1,0,0,NaN
703758,716833,I’m not sure what you’re arguing for here. Are...,False,1527807928,t3_8nlb03,t1_dzwnkbs,-1,1,0,NaN
703759,716834,[deleted],False,1527795686,t3_8nldhs,t1_dzwcbs9,-1,1,0,NaN
703760,716835,There's a difference between making a profit a...,False,1527796576,t3_8nldhs,t1_dzwdej6,-1,0,0,NaN
703761,716836,[deleted],False,1527797084,t3_8nldhs,t1_dzwdsmx,-1,0,0,NaN
703762,716837,What? What does Mario have to do with Greco-Ro...,False,1527806534,t3_8nlgf7,t3_8nlgf7,-1,1,0,NaN
703763,716838,"Yeah I think I'll be skipping this one, I was ...",False,1527797512,t3_8nlkcy,t3_8nlkcy,-1,1,0,NaN
703764,716839,Oh I still am along with BF 1 .. I'm not gonna...,False,1527798176,t3_8nlkcy,t1_dzwf6rr,-1,0,0,NaN
703765,716840,Blood borne if you want to hate yourself and e...,False,1527797921,t3_8nlm5z,t3_8nlm5z,-1,0,0,NaN
703766,716841,You got a fireplace? Throw those top two in t...,False,1527808395,t3_8nlm5z,t3_8nlm5z,-1,0,0,NaN
703767,716842,Damn Peer looks young.,False,1527803761,t3_8nltol,t3_8nltol,-1,0,0,NaN
703768,716844,RIP,False,1527801581,t3_8nm13q,t3_8nm13q,-1,1,0,NaN
703769,716845,r/jokes,False,1527803182,t3_8nmavf,t1_dzwk245,-1,0,0,NaN
703770,716846,Why lol?,False,1527806555,t3_8nmesi,t1_dzwo0mc,-1,0,0,NaN
703771,716847,"Well, 1,4 ghz cpu laptops aren't exactly $300....",False,1527804449,t3_8nmfj0,t1_dzwlher,-1,0,0,NaN
703772,716848,"After you, kind sir !",False,1527803818,t3_8nmfl2,t1_dzwl8xx,-1,0,0,NaN
703773,716849,"that game is a slog, i was pissed when i bough...",False,1527808634,t3_8nmh5r,t1_dzwp95s,-1,1,0,NaN
703774,716850,[deleted],False,1527805266,t3_8nmh5r,t3_8nmh5r,-1,0,0,NaN
703775,716851,My mouth actually dropped when I saw mgs3 rema...,False,1527805813,t3_8nmni0,t3_8nmni0,-1,0,0,NaN
703776,716852,A bit boring. Maybe real? Snake Eater remake s...,False,1527805944,t3_8nmni0,t3_8nmni0,-1,0,0,NaN
703777,716853,Don’t use a budget GTA font. It looks like you...,False,1527806514,t3_8nmrfm,t3_8nmrfm,-1,1,0,NaN
703778,716854,Eh could be better \n\n\n\n\n\n/s,False,1527809063,t3_8nmst7,t3_8nmst7,-1,0,0,NaN
703779,716855,Plague inc,False,1527808116,t3_8nmwun,t3_8nmwun,-1,0,0,NaN
703780,716856,WTf its not my channel...,False,1527810779,t3_8nn76h,t1_dzwrvx5,-1,0,0,NaN
703781,716857,My money is still on witcher 3.,False,1527810428,t3_8nn8f7,t3_8nn8f7,-1,0,0,NaN

Hidden scores are basically useless to us.  Why?  Because they are essentially unlabelled and given the default score of 1, so we will not be able to train a model on them.  Additionally, it does not make sense to manually "label" them by giving them a score because then we would be making the model inaccurate by including our own arbitrary biases to it.  Thus, we remove them.

In [58]:
# remove all hidden scores
comments = comments[comments.score_hidden != True]

# check that it worked
comments["score_hidden"].unique()

array([False])

In [59]:
# reset the index for possible future use
comments.reset_index()

,index,body,score_hidden,created_utc,link_id,parent_id,score,controversiality,gilded,distinguished
0,0,"Lol come on kid, you don't have to act tough. ...",False,1525438018,t3_7bpgu4,t1_dyfffkj,0,0,0,NaN
1,1,"There were soany disappointments in GTA5, the ...",False,1525419638,t3_7bpgu4,t1_dy2jctt,0,0,0,NaN
2,2,If it's very likely that your friends and fami...,False,1525246808,t3_7by7xx,t1_dpmatdi,0,0,0,NaN
3,3,I had no idea this was here! Is it taboo to re...,False,1526059024,t3_7e675r,t1_dytfbys,0,0,0,NaN
4,4,If I recall correctly the DNC candidate last p...,False,1525731042,t3_7ek4q6,t1_dq5t2ri,0,0,0,NaN
5,5,Not going to argue when you cant even see it y...,False,1525957030,t3_7fo1rm,t1_dyhg867,0,0,0,NaN
6,6,It's a fucking 14 year old.....,False,1525962054,t3_7g1chd,t1_dqg6i5o,0,0,0,NaN
7,7,*cough* *cough* skyrim *cough*,False,1525463027,t3_7m08f4,t1_dygc6pv,0,0,0,NaN
8,8,"As much as i love both campaigns, you gotta re...",False,1525431827,t3_7m08f4,t1_drr5l6c,0,0,0,NaN
9,9,Developers want to make everything more multip...,False,1525454093,t3_7m08f4,t1_dyfw7u9,0,0,0,NaN
10,10,Wah wah wah.,False,1527006133,t3_7m1hei,t1_dv3d9q3,0,0,0,NaN
11,11,These 12 games is all they have almost a year ...,False,1525997695,t3_7n83n9,t1_drzunwh,0,0,0,NaN
12,12,"My subreddit recommendation game is top-notch,...",False,1527635187,t3_7p96u4,t1_dzshx32,0,0,0,NaN
13,13,"Nope.\n\n&gt;Welcome to /r/dontdeadopeninside,...",False,1527634652,t3_7p96u4,t1_dsfgk9p,0,0,0,NaN
14,14,No it wasn’t. Theoretically they could have go...,False,1525418690,t3_7x18az,t1_du5gxwh,0,0,0,NaN
15,15,never really played a Zelda. And to be honest...,False,1525422800,t3_7xtnmw,t1_dub8zqs,0,0,0,NaN
16,16,Only the fortnite wins matter not the grades,False,1527474941,t3_7xurnb,t1_dubgu8r,0,0,0,NaN
17,17,[deleted],False,1527146433,t3_7y2psy,t1_dzh47v5,0,0,0,NaN
18,18,[deleted],False,1527114736,t3_7y2psy,t1_dzgkmg2,0,0,0,NaN
19,19,"Opioids*.\n \nGo back to English class, stalke...",False,1527186840,t3_7y2psy,t1_dzhp57d,0,0,0,NaN
20,20,You weren't right and edited your comment to c...,False,1527121097,t3_7y2psy,t1_dzgy3t3,0,0,0,NaN
21,21,living with dial-up connection or better livin...,False,1526500783,t3_7yz15s,t1_dz3b2x9,0,0,0,NaN
22,22,Also I think this post should be kept alive. E...,False,1526532518,t3_7yz15s,t1_dz3b2x9,0,0,0,NaN
23,23,Mine still works fine\n,False,1527197971,t3_7yzs17,t1_dulalpy,0,0,0,NaN
24,24,"No,they're pocket monster not pocket animals.",False,1526038989,t3_7zr4rf,t1_duqkdrp,0,0,0,NaN
25,25,&gt;I've been a lot of places in my lifetime. ...,False,1527019312,t3_804p3s,t1_dutl09j,0,0,0,NaN
26,26,Just use GeForce experience optimization then,False,1525723890,t3_80e68k,t1_duuvdgy,0,0,0,NaN
27,27,Damn if only 8=====D \n\nYou’re the bitch boy ...,False,1525335214,t3_81k66k,t1_dy6nxv4,0,0,0,NaN
28,28,"That would be Yahtzee, from the channel zero p...",False,1527419858,t3_82qos7,t1_dvc2dps,0,0,0,NaN
29,29,68 days to come up with that response. Nice.,False,1526597901,t3_83a7ww,t1_dz5nera,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...
702962,716827,You cant really know that can you? Because the...,False,1527791474,t3_8nkn3v,t1_dzw7i80,-1,0,0,NaN
702963,716828,Has anyone ever modded one of these to run on ...,False,1527795580,t3_8nkzdi,t3_8nkzdi,-1,0,0,NaN
702964,716829,"Same desktop picture -1, task bar on both scre...",False,1527797681,t3_8nl3tq,t3_8nl3tq,-1,0,0,NaN
702965,716830,Ps4 sucks. Controllers are terrible,False,1527795131,t3_8nl6pc,t3_8nl6pc,-1,0,0,NaN
702966,716831,"Now Billy, the normies are listening, and i kn...",False,1527795296,t3_8nlb03,t3_8nlb03,-1,1,0,NaN
702967,716832,The dream police \nThey live inside of my hea...,False,1527810969,t3_8nlb03,t3_8nlb03,-1,0,0,NaN
702968,716833,I’m not sure what you’re arguing for here. Are...,False,1527807928,t3_8nlb03,t1_dzwnkbs,-1,1,0,NaN
702969,716834,[deleted],False,1527795686,t3_8nldhs,t1_dzwcbs9,-1,1,0,NaN
702970,716835,There's a difference between making a profit a...,False,1527796576,t3_8nldhs,t1_dzwdej6,-1,0,0,NaN
702971,716836,[deleted],False,1527797084,t3_8nldhs,t1_dzwdsmx,-1,0,0,NaN
702972,716837,What? What does Mario have to do with Greco-Ro...,False,1527806534,t3_8nlgf7,t3_8nlgf7,-1,1,0,NaN
702973,716838,"Yeah I think I'll be skipping this one, I was ...",False,1527797512,t3_8nlkcy,t3_8nlkcy,-1,1,0,NaN
702974,716839,Oh I still am along with BF 1 .. I'm not gonna...,False,1527798176,t3_8nlkcy,t1_dzwf6rr,-1,0,0,NaN
702975,716840,Blood borne if you want to hate yourself and e...,False,1527797921,t3_8nlm5z,t3_8nlm5z,-1,0,0,NaN
702976,716841,You got a fireplace? Throw those top two in t...,False,1527808395,t3_8nlm5z,t3_8nlm5z,-1,0,0,NaN
702977,716842,Damn Peer looks young.,False,1527803761,t3_8nltol,t3_8nltol,-1,0,0,NaN
702978,716844,RIP,False,1527801581,t3_8nm13q,t3_8nm13q,-1,1,0,NaN
702979,716845,r/jokes,False,1527803182,t3_8nmavf,t1_dzwk245,-1,0,0,NaN
702980,716846,Why lol?,False,1527806555,t3_8nmesi,t1_dzwo0mc,-1,0,0,NaN
702981,716847,"Well, 1,4 ghz cpu laptops aren't exactly $300....",False,1527804449,t3_8nmfj0,t1_dzwlher,-1,0,0,NaN
702982,716848,"After you, kind sir !",False,1527803818,t3_8nmfl2,t1_dzwl8xx,-1,0,0,NaN
702983,716849,"that game is a slog, i was pissed when i bough...",False,1527808634,t3_8nmh5r,t1_dzwp95s,-1,1,0,NaN
702984,716850,[deleted],False,1527805266,t3_8nmh5r,t3_8nmh5r,-1,0,0,NaN
702985,716851,My mouth actually dropped when I saw mgs3 rema...,False,1527805813,t3_8nmni0,t3_8nmni0,-1,0,0,NaN
702986,716852,A bit boring. Maybe real? Snake Eater remake s...,False,1527805944,t3_8nmni0,t3_8nmni0,-1,0,0,NaN
702987,716853,Don’t use a budget GTA font. It looks like you...,False,1527806514,t3_8nmrfm,t3_8nmrfm,-1,1,0,NaN
702988,716854,Eh could be better \n\n\n\n\n\n/s,False,1527809063,t3_8nmst7,t3_8nmst7,-1,0,0,NaN
702989,716855,Plague inc,False,1527808116,t3_8nmwun,t3_8nmwun,-1,0,0,NaN
702990,716856,WTf its not my channel...,False,1527810779,t3_8nn76h,t1_dzwrvx5,-1,0,0,NaN
702991,716857,My money is still on witcher 3.,False,1527810428,t3_8nn8f7,t3_8nn8f7,-1,0,0,NaN

Now we work on the "distinguished" column.  We conduct a quick inspection to see what the column actually contains.

In [60]:
# what values are in the column
comments["distinguished"].unique()

array([nan, 'moderator'], dtype=object)

We can see that the column basically shows whether a comment was made by a moderator or not.  We can analyze this variable later (ie. whether a comment made by a moderator results in a higher score or not) but for now, we need to replace the null values, the value that shows that the comment was not made by a moderator, with a value such as 0 and replace the "moderator" with another value such as 1.  This effectively means that we dummy code our data.

In [61]:
# convert all values in the "distinguished" column
comments["distinguished"].fillna(0, inplace = True)

# convert the "moderator" values
for value in comments["distinguished"]:
    if value == "moderator":
        value = 1

# check to see if this is done correctly
1 in comments["distinguished"]

True

We also rename the column to "is_moderator_comments" to make it easier to remember what the values in the column represent and that it is from the comments dataset.

In [62]:
# rename the column to "is_moderator"
comments.rename(columns = {'distinguished': 'is_moderator_comments'}, inplace=True)

# check to make sure it executed properly
comments.head()

,body,score_hidden,created_utc,link_id,parent_id,score,controversiality,gilded,is_moderator_comments
0,"Lol come on kid, you don't have to act tough. ...",False,1525438018,t3_7bpgu4,t1_dyfffkj,0,0,0,0
1,"There were soany disappointments in GTA5, the ...",False,1525419638,t3_7bpgu4,t1_dy2jctt,0,0,0,0
2,If it's very likely that your friends and fami...,False,1525246808,t3_7by7xx,t1_dpmatdi,0,0,0,0
3,I had no idea this was here! Is it taboo to re...,False,1526059024,t3_7e675r,t1_dytfbys,0,0,0,0
4,If I recall correctly the DNC candidate last p...,False,1525731042,t3_7ek4q6,t1_dq5t2ri,0,0,0,0

Next, we have to convert the values in the "created_utc" from a POSIX timestamp to something human readable.

In [63]:
# convert the timestamps using the datetime module
comments["created_utc"] = comments["created_utc"].apply(datetime.utcfromtimestamp)

In [64]:
# check to see how it executed
comments.head()

,body,score_hidden,created_utc,link_id,parent_id,score,controversiality,gilded,is_moderator_comments
0,"Lol come on kid, you don't have to act tough. ...",False,2018-05-04 12:46:58,t3_7bpgu4,t1_dyfffkj,0,0,0,0
1,"There were soany disappointments in GTA5, the ...",False,2018-05-04 07:40:38,t3_7bpgu4,t1_dy2jctt,0,0,0,0
2,If it's very likely that your friends and fami...,False,2018-05-02 07:40:08,t3_7by7xx,t1_dpmatdi,0,0,0,0
3,I had no idea this was here! Is it taboo to re...,False,2018-05-11 17:17:04,t3_7e675r,t1_dytfbys,0,0,0,0
4,If I recall correctly the DNC candidate last p...,False,2018-05-07 22:10:42,t3_7ek4q6,t1_dq5t2ri,0,0,0,0

And with that, we have a readable set of timestamps in the "created_utc" column.

Lastly, we have to check the dataset for missing data.  Missing data with hinder our analysis and modelling later on.

In [65]:
# missing data check
comments.apply(lambda x: sum(x.isnull()), axis=0)

body                     7
score_hidden             0
created_utc              0
link_id                  0
parent_id                0
score                    0
controversiality         0
gilded                   0
is_moderator_comments    0
dtype: int64

We can see from the results that we are missing data in 7 of body rows.  However, since it is basically impossible to replace these values with any actual values, we are forced to simply delete them from the dataset.

In [66]:
# remove the rows from the dataset
comments = comments[comments.body.notnull()]

In [67]:
# check to make sure that the rows have been properly removed
comments.apply(lambda x: sum(x.isnull()), axis=0)

body                     0
score_hidden             0
created_utc              0
link_id                  0
parent_id                0
score                    0
controversiality         0
gilded                   0
is_moderator_comments    0
dtype: int64

With this, we have finished cleaning up the comments dataset.

# Cleaning Posts

We clean up posts so that when we combine the datasets, there won't be an absurd number of columns to look through.  Thankfully, there isn't as much to clean up here.

In [78]:
# construct a list containing all columns to be dropped
drop_list_posts = ["author", "url", "ups", "downs", "selftext", "from_kind", "from", "thumbnail", "subreddit", "hide_score",
                  "link_flair_css_class", "author_flair_css_class", "archived", "is_self", "from_id", "permalink",
                  "author_flair_text", "quarantine", "link_flair_text", "retrieved_on", "subreddit_id", "saved"]

# execute the drop
posts.drop(drop_list_posts, axis = 1, inplace = True)

# view the remainder
posts.head()

,created_utc,domain,num_comments,score,title,id,gilded,stickied,over_18,name,distinguished
0,1525653984,hh,0,1,yy,8hjnmt,0,False,False,t3_8hjnmt,NaN
1,1527269415,if,0,1,Jeu,8m3k8c,0,False,False,t3_8m3k8c,NaN
2,1527613615,t.me,0,1,I've build a little telegram channel operated ...,8n0rgh,0,False,False,t3_8n0rgh,NaN
3,1526617219,nu.nl,0,1,EA Sports is forbidden to advertise lootboxes ...,8kagur,0,False,False,t3_8kagur,NaN
4,1527150738,nu.nl,0,1,PlayStation 5 verschijnt op zijn vroegst in 2021,8lr2qw,0,False,False,t3_8lr2qw,NaN

Once again, we have a distinguished column that needs to be cleaned.

In [79]:
# check the present values
posts["distinguished"].unique()

array([nan])

In this case, since the column literally holds nothing of value, we can just delete it instead of cleaning it.

In [80]:
# delete the column
posts.drop("distinguished", axis = 1, inplace = True)
posts.head()

,created_utc,domain,num_comments,score,title,id,gilded,stickied,over_18,name
0,1525653984,hh,0,1,yy,8hjnmt,0,False,False,t3_8hjnmt
1,1527269415,if,0,1,Jeu,8m3k8c,0,False,False,t3_8m3k8c
2,1527613615,t.me,0,1,I've build a little telegram channel operated ...,8n0rgh,0,False,False,t3_8n0rgh
3,1526617219,nu.nl,0,1,EA Sports is forbidden to advertise lootboxes ...,8kagur,0,False,False,t3_8kagur
4,1527150738,nu.nl,0,1,PlayStation 5 verschijnt op zijn vroegst in 2021,8lr2qw,0,False,False,t3_8lr2qw

Our "created_utc" column is also here so we need to convert it to a readable format as well.

In [84]:
# convert the timestamps using the datetime module
posts["created_utc"] = posts["created_utc"].apply(datetime.utcfromtimestamp)

We also have to check for missing data in any other part of the dataframe.

In [85]:
# missing data check
posts.apply(lambda x: sum(x.isnull()), axis=0)

created_utc     0
domain          0
num_comments    0
score           0
title           0
id              0
gilded          0
stickied        0
over_18         0
name            0
dtype: int64

Since there is no missing data, we are done cleaning this dataset.

# Combining datasets

Only the titles of the posts dataset is of interest to us.  We want to combine them with our comments dataset so each comment is associated with a post title.  To do this, we can match the comment's "parent_id" with the "name" of the post.

In [86]:
# merge the dataframes together
merged_dataframe = pd.merge(comments, posts, left_on = "parent_id", right_on = "name", how = "inner")

In [87]:
# check the merged dataset
merged_dataframe.head()

,body,score_hidden,created_utc_x,link_id,parent_id,score_x,controversiality,gilded_x,is_moderator_comments,created_utc_y,domain,num_comments,score_y,title,id,gilded_y,stickied,over_18,name
0,And yet we are still bombing the shit out of o...,False,2018-05-01 00:38:18,t3_8g46zh,t3_8g46zh,0,0,0,0,2018-05-01 00:07:16,i.redd.it,6,13,This Game Boy was damaged when barracks were b...,8g46zh,0,False,False,t3_8g46zh
1,Can’t deny that Nintendo products are built to...,False,2018-05-01 00:11:56,t3_8g46zh,t3_8g46zh,0,1,0,0,2018-05-01 00:07:16,i.redd.it,6,13,This Game Boy was damaged when barracks were b...,8g46zh,0,False,False,t3_8g46zh
2,I wonder if the owner survived.,False,2018-05-01 04:26:31,t3_8g46zh,t3_8g46zh,1,0,0,0,2018-05-01 00:07:16,i.redd.it,6,13,This Game Boy was damaged when barracks were b...,8g46zh,0,False,False,t3_8g46zh
3,This was at the Nintendo Store in NYC,False,2018-05-01 00:23:45,t3_8g46zh,t3_8g46zh,4,0,0,0,2018-05-01 00:07:16,i.redd.it,6,13,This Game Boy was damaged when barracks were b...,8g46zh,0,False,False,t3_8g46zh
4,can we bomb this shit out of this post before ...,False,2018-05-01 01:09:22,t3_8g46zh,t3_8g46zh,5,0,0,0,2018-05-01 00:07:16,i.redd.it,6,13,This Game Boy was damaged when barracks were b...,8g46zh,0,False,False,t3_8g46zh

With this, we have merged the 2 datasets together.  Any value with an "x" appended to the end of the column name is from the comments dataframe whilst anything with a "y" is from the posts dataframe.

# Touch Up

Now that the datasets have been combined, we can delete a few more rows.  We kept rows such as "link_id" and "name" because we could use them to merge our datasets.

In [88]:
# list of rows to delete
drop_merged_dataframe = ["link_id", "name", "parent_id", "id", "name"]

# delete the now useless rows
merged_dataframe.drop(drop_merged_dataframe, axis = 1, inplace = True)

In [89]:
# check the execution
merged_dataframe.head()

,body,score_hidden,created_utc_x,score_x,controversiality,gilded_x,is_moderator_comments,created_utc_y,domain,num_comments,score_y,title,gilded_y,stickied,over_18
0,And yet we are still bombing the shit out of o...,False,2018-05-01 00:38:18,0,0,0,0,2018-05-01 00:07:16,i.redd.it,6,13,This Game Boy was damaged when barracks were b...,0,False,False
1,Can’t deny that Nintendo products are built to...,False,2018-05-01 00:11:56,0,1,0,0,2018-05-01 00:07:16,i.redd.it,6,13,This Game Boy was damaged when barracks were b...,0,False,False
2,I wonder if the owner survived.,False,2018-05-01 04:26:31,1,0,0,0,2018-05-01 00:07:16,i.redd.it,6,13,This Game Boy was damaged when barracks were b...,0,False,False
3,This was at the Nintendo Store in NYC,False,2018-05-01 00:23:45,4,0,0,0,2018-05-01 00:07:16,i.redd.it,6,13,This Game Boy was damaged when barracks were b...,0,False,False
4,can we bomb this shit out of this post before ...,False,2018-05-01 01:09:22,5,0,0,0,2018-05-01 00:07:16,i.redd.it,6,13,This Game Boy was damaged when barracks were b...,0,False,False

# Export the dataset

Now we have to export the completed dataset so that we can conduct analysis on it in another notebook.

In [90]:
# export the dataset
merged_dataframe.to_csv("cleaned_subreddit_gaming.csv", encoding = "utf-8")

# Conclusion

Overall, we have cleaned 2 seperate but related datasets and used common values in a column to merge the 2 datasets.  This has given us a single dataset that is smaller than the original 2, but that we can also now conduct analysis and modelling on as required.